### ISSUE TITLE
Hbs blog page speed

### ISSUE THREAD

**Issue by keybasegit** [hbstack/theme#22] opened 2023-04-09 15:09 UTC
HBS landing page speed is excellent. Doc section page speed decrease on mobile platform. Blog page speed on mobile platform is still lower due to img, several.js, comments section, gravatar, etc. https://pagespeed.web.dev/analysis/https-hb-theme-hugomods-com-en-blog-2023-03-tutorial/jjkbaq6n9w?form_factor=mobile
  If it should be than it is.

**Comment by razonyang** [comment] 2023-04-09 22:08
Will check, but there is less thing to do, most issues caused by third parties.

**Comment by razonyang** [comment] 2023-04-10 03:04
Made some improvements, result https://pagespeed.web.dev/analysis/https-hb-theme-hugomods-com-en-blog-2023-03-tutorial/i50mlb88o6?form_factor=mobile

> You need to upgrade modules via `hugo mod get -u`

There is less thing we can do for other issues come from third parties, that page includes a lot of resources, such as KaTex, Mermaid and Giscus.

Please close this issue if you're comfortable with the result, or share any ideas on this topic to make it forward.

**Comment by keybasegit** [comment] 2023-04-10 15:22
Issue closed.

**Closed** 2023-04-10 15:24 UTC
